### ISSUE TITLE
Verify your GitHub

### ISSUE THREAD

**Issue by Zbee** [Zbee/Abian#2]
Leave a comment on this issue with your unique code to verify your GitHub account and Abian mods will go through and verify your accounts.

PLEASE leave a comment here within an hour of changing your GitHub name on Abian.

I'm trying to automate this, so that Abian will automatically verify your GitHub name by just asking to look at your account through the GitHub, but that hasn't happened yet.

**Comment by Zbee** [comment]
20ee51a

**Comment by Zbee** [comment]
@Zbee verified

**Comment by NJRT59** [comment]
it worked

**Comment by Zbee** [comment]
@NJRT59 What did?

**Comment by NJRT59** [comment]
Sorry wrong person

**Comment by Zbee** [comment]
No longer needed, next commit will include a change to the user control panel where users just click a button to add their GitHub name (asks user to access their public profile, GitHub tells Abian their username).
